# predictor.py
"""Data loading and prediction utilities for the FPL Scout web API.
This module is deliberately UI‑agnostic so it can be imported by the
FastAPI backend as well as any future scripts.
"""

import os
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Path to the CSV generated by the notebook
CSV_PATH = "fpl_data.csv"


def load_from_csv():
    """Load player data from the CSV.
    Returns a list of dictionaries, one per player.
    Raises FileNotFoundError if the CSV is missing.
    """
    if not os.path.exists(CSV_PATH):
        raise FileNotFoundError(
            f"'{CSV_PATH}' not found. Run the notebook first to generate it."
        )
    df = pd.read_csv(CSV_PATH)
    return df.to_dict(orient="records")


def predict_player(player, all_players, games_left=8):
    """Predict future statistics for a single player.

    Parameters
    ----------
    player: dict
        The player record to forecast.
    all_players: list[dict]
        Full dataset, used for training the model.
    games_left: int, optional
        Number of remaining gameweeks (default 8).

    Returns
    -------
    list[dict]
        Forecast entries, each containing ``name``, ``current``, ``future``,
        ``final``, ``rate`` and ``games``.
    """
    pos = player.get("position_name")
    # Configuration mirrors the original GUI constants
    POSITION_CONFIG = {
        "GKP": {
            "features": ["expected_goals_conceded", "minutes"],
            "targets": [("saves", "Saves"), ("clean_sheets", "Clean Sheets")],
        },
        "DEF": {
            "features": ["defensive_contribution", "influence", "minutes"],
            "targets": [("clearances_blocks_interceptions", "CBI"), ("clean_sheets", "Clean Sheets")],
        },
        "MID": {
            "features": ["expected_assists", "creativity", "influence"],
            "targets": [("assists", "Assists"), ("expected_goal_involvements", "xGI")],
        },
        "FWD": {
            "features": ["threat", "expected_goal_involvements", "expected_goals"],
            "targets": [("goals_scored", "Goals"), ("expected_goals", "xG")],
        },
    }
    cfg = POSITION_CONFIG.get(pos)
    if not cfg:
        return []

    # Filter dataset to same position and valid numeric rows
    position_df = [p for p in all_players if p.get("position_name") == pos]
    valid = [p for p in position_df if all(isinstance(p.get(f), (int, float)) for f in cfg["features"]) and isinstance(p.get(cfg["targets"][0][0]), (int, float))]
    # Ensure enough data
    if len(valid) < 5:
        return []

    # Build feature matrix and target vectors for each forecast metric
    forecasts = []
    minutes = player.get("minutes") or 0
    matches_played = max(minutes / 90, 0.1)
    for target_col, target_name in cfg["targets"]:
        X = np.array([[p[f] for f in cfg["features"]] for p in valid])
        y = np.array([p[target_col] for p in valid])
        x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        model = RandomForestRegressor(n_estimators=100, random_state=42)
        model.fit(x_train, y_train)
        player_feat = np.array([[player.get(f, 0) for f in cfg["features"]]])
        predicted = model.predict(player_feat)[0]
        rate = predicted / matches_played
        future = rate * games_left
        current = player.get(target_col) or 0
        final = current + future
        forecasts.append({
            "name": target_name,
            "current": current,
            "rate": rate,
            "future": future,
            "final": final,
            "games": games_left,
        })
    return forecasts
